### ISSUE TITLE
Unable to install binaryen and wabt on Debian 9

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/substrate-contracts-workshop#1]
When I follow the steps on this page https://shawntabrizi.github.io/substrate-contracts-workshop/#/0/setup, and I enter these commands
```
sudo apt install binaryen
sudo apt install wabt
````

It returns errors:
```
E: Unable to locate package wabt
E: Unable to locate package binaryen
```

If I run `apt update` first, and then run the commands, it still gives me the same error.

Linux users may not need to install these dependencies.

**Comment by lsaether** [comment]
> Linux users may not need to install these dependencies.
@ltfschoen are you able to confirm / deny that?

Using Arch Linux I installed these dependencies from the community packages and AUR, but it might come bundled with Ubuntu / Debian distros?

**Comment by ascjones** [comment]
I had to install these from source on Ubuntu (18.10)

**Comment by riusricardo** [comment]
There is an alternative way to install the required binaries.
[Add Wasm tools script PR #81](https://github.com/paritytech/scripts/pull/81/files)

**storage.googleapis.com/wasm-llvm/builds** is the default storage location used by the up-to-date Webassembly installation process.  https://webassembly.org/getting-started/developers-guide/
