### ISSUE TITLE
Confusion coming to "smart ink" tutorial after "contract pallet" tutorial   

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/substrate-contracts-workshop#100]
So I had just completed the "contract pallet" tutorial at https://substrate.dev/docs/en/tutorials/add-contracts-pallet/ and I was keen to try out a smart contract, so I followed the advice at the end of the tutorial:

> With your node now capable of running smart contracts, go learn about Substrate ink! smart contracts.

Which is what lead me to this tutorial, where I have now been able to compile the example "flipper" smart contract.  Then on [this page](https://substrate.dev/substrate-contracts-workshop/#/0/running-a-substrate-node) it says I should run a node locally with:

```
canvas --dev --tmp
```

which doesn't work for me - I'm also unclear which directory to run it in.  I have the `substrate-node-template` directory from the "contracts pallet" tutorial, which is where I was running back end nodes previously.  The `canvas` command doesn't work there, but the command that I used in the "contracts pallet" does.  That command is:

```
./target/release/node-template --dev --tmp
```

The expected output from running `canvas` looks very similar to what I get running the `node-template` command so I tried to continue on in the tutorial, which tells me to use https://paritytech.github.io/canvas-ui which is supposed to be able to connect to local nodes.

When I open it I get a  different front end than I was using previously, and requires extra permissions in my browser …

There I don’t see any of the backend accounts that I was seeing in my previous front end (alice, bob etc.) - but I do see the one I created using the firefox plugin.  I was able to upload my contract, but I get this error:

> contracts.putCode
> 1010: Invalid Transaction: Inability to pay some fees, e.g. account balance too low

so I feel like this is somehow trying to work with the real network, not my test one ….  can anyone help me understand how to proceed here?

**Comment by mfreeman451** [comment]
try running without -tmp mode

**Comment by tansaku** [comment]
thanks @mfreeman451 - your tip in element was the trick: 

> lower left corner, switch to "local node"

![Screenshot 2021-02-11 at 17 38 50](https://user-images.githubusercontent.com/30216/107675714-442fb600-6c90-11eb-88ef-2ea615ecba19.png)

That allows me to upload the flipper contract for "alice":

![Screenshot 2021-02-11 at 17 41 22](https://user-images.githubusercontent.com/30216/107675914-79d49f00-6c90-11eb-81d5-70d6ec0ab6c7.png)

but that moves me on to a different error:

![Screenshot 2021-02-11 at 17 41 39](https://user-images.githubusercontent.com/30216/107675982-8d800580-6c90-11eb-8d7f-528b335ae654.png)

which looks like the same error when I had a 2.0.0 front end 2.0.1 back end mismatch issue ...

**Comment by mfreeman451** [comment]
Might need to see the contract and see what 'tx' is? Check the source code compare what enum's MultiAddress supports

**Comment by tansaku** [comment]
thanks @mfreeman451 - so the contract is just the standard flipper contract built according to the instructions here https://substrate.dev/substrate-contracts-workshop/#/0/building-your-contract - I've put it up here:

https://github.com/tansaku/flipper/blob/main/lib.rs

there's no mention of tx or multiaddress in it at all.

Where I did see this error before was in a mismatch between a 2.0.0 frontend and a 2.0.1 backend (which was the only one I could get running on my MBP)

I put in a PR to the subtrate tutorials for that that got merged:

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/830

and was discussed in some detail in 

https://github.com/substrate-developer-hub/substrate-front-end-template/issues/158

which makes me think that things might not work until https://paritytech.github.io/canvas-ui gets an upgrade ...?

**Comment by tansaku** [comment]
Just to note that I've got this all working now - I had been trying to get the canvas front end to talk to a substrate back end node.  It all works smoothly for me when I use the canvas-node backend and canvas front end
