### ISSUE TITLE
Deploying "Flipper" contract from tutorial fails with "1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low" error

### ISSUE THREAD

**Issue by vbeffa** [substrate-developer-hub/substrate-contracts-workshop#101]
Following the steps here:

https://substrate.dev/substrate-contracts-workshop/#/0/deploying-your-contract

results in this:

![Screen Shot 2021-02-11 at 2 29 03 PM](https://user-images.githubusercontent.com/6473744/107694963-e1e2af80-6ca7-11eb-9b42-77470bc5df32.png)

**Comment by cmichi** [comment]
@vbeffa The screenshot on the workshop page shows "Alice" as the account. It should work if you select that one.

**Comment by vbeffa** [comment]
You are correct. I didn't see any accounts after installing the polkadot extension and I assumed I had to create one. I see Alice now. Thank you.
