### ISSUE TITLE
Potential bug in the contract?

### ISSUE THREAD

**Issue by gurghet** [substrate-developer-hub/substrate-contracts-workshop#102]
In the ERC20 contract, the `transfer_from` function, provided there is enough allowance, deducts from the allowance even if the balance is insufficient.

```
#[ink::test]
        fn transfer_from_works_even_when_balance_insufficient() {
            let mut contract = Erc20::new(100);
            assert_eq!(contract.balance_of(AccountId::from([0x1; 32])), 100);
            contract.approve(AccountId::from([0x1; 32]), 20);
            contract.transfer(AccountId::from([0x2; 32]), 95);
            contract.transfer_from(AccountId::from([0x1; 32]), AccountId::from([0x0; 32]), 10);
            assert_eq!(contract.balance_of(AccountId::from([0x0; 32])), 0);
            assert_eq!(contract.allowance(AccountId::from([0x1; 32]), AccountId::from([0x1; 32])), 20);
        }
```

<img width="700" alt="Снимок экрана 2021-02-20 193247" src="https://user-images.githubusercontent.com/420735/108606533-789f2280-73b2-11eb-932a-1ed7e7a598cf.png">

Is this behavior expected?

**Comment by korzewski** [comment]
This is my assumption as well, I have created this PR to solve it https://github.com/substrate-developer-hub/substrate-contracts-workshop/pull/107

**Comment by cmichi** [comment]
@gurghet Thanks for reporting!

Closed with https://github.com/substrate-developer-hub/substrate-contracts-workshop/pull/107.
