### ISSUE TITLE
Installing Canvas note generates Filename collision and exits build process

### ISSUE THREAD

**Issue by DjangoMaker** [substrate-developer-hub/substrate-contracts-workshop#121]
When I follow the setup and use the command:
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.5 --force --locked

After a while the build process errors out with filename collision.  I've tried building it twice with same error. I'm running this on a terminal on windows 10 running WSL ubuntu 20

[canvas-node.txt](https://github.com/substrate-developer-hub/substrate-contracts-workshop/files/6361142/canvas-node.txt)

**Comment by cmichi** [comment]
@DjangoMaker Have you followed the setup [from here](https://substrate.dev/substrate-contracts-workshop/#/0/setup)? 

There is this at the end of the log file which you posted:
```
the `wasm32-unknown-unknown` target may not be installed
```
Could you try executing
```
rustup component add rust-src --toolchain nightly
rustup target add wasm32-unknown-unknown --toolchain stable
```
before your install?

**Comment by DjangoMaker** [comment]
> ```
> rustup component add rust-src --toolchain nightly
> rustup target add wasm32-unknown-unknown --toolchain stable
> ```
> 
> before your install?
Yes, I did that before, as per install instructions I was following step by step from this page: 
https://substrate.dev/substrate-contracts-workshop/#/0/setup

**Comment by nuke-web3** [comment]
Looks like we are set here? If not, please let's open a new issue and reference this in:
https://github.com/substrate-developer-hub/substrate-docs/issues/
