### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by cmichi** [substrate-developer-hub/substrate-contracts-workshop#127]
@jimmychu0807 For me the images in `assets` are currently broken. Could this be a result of your PR?

See e.g. https://substrate.dev/substrate-contracts-workshop/#/ or https://substrate.dev/substrate-contracts-workshop/#/0/troubleshooting.

When I try to access one of the `png`'s I get this:
```
$ curl https://substrate.dev/substrate-contracts-workshop/0/assets/send-as.png
version https://git-lfs.github.com/spec/v1
oid sha256:1a6a72c48f1caa962be3c23f65c703a18aa9c0f28a191b6def381f53e4d4c159
size 82828
```

**Comment by jimmychu0807** [comment]
It works when running locally. It has something to do about github page environment and need some experimentation pushing to master to deploy to gh-page. As you point out, maybe gh-page is not supporting lfs object well.

**Comment by jimmychu0807** [comment]
I reverted the git-lfs object, and all images load properly. Try using an incognito window to ensure the browser is not using the cached images:

https://substrate.dev/substrate-contracts-workshop/

**Comment by cmichi** [comment]
Thanks, Jimmy! What was your original intention with the git-lfs change, why would it be better?
