### ISSUE TITLE
Broken link in Contract Development workshop

### ISSUE THREAD

**Issue by NickitaX** [substrate-developer-hub/substrate-contracts-workshop#129]
https://substrate.dev/substrate-contracts-workshop/#/2/testing?id=next-step

![image](https://user-images.githubusercontent.com/11023063/121781351-986b8800-cbe7-11eb-9a37-8b3db32d83a9.png)

When following this link it fails with 404.

Any suggestion for a valid redirect link?

**Comment by cmichi** [comment]
I just tried it and it seems to work now: https://substrate.dev/docs/en/knowledgebase/smart-contracts/. Maybe a temporary hiccup, I think there is work done on substrate.dev currently.
