### ISSUE TITLE
How to launch canvas so as to listen to external IP instead of 127.0.0.1:9944

### ISSUE THREAD

**Issue by claudiociardelli** [substrate-developer-hub/substrate-contracts-workshop#133]
Hello,
Compiled canvas on a remote VPS running and Ubutu server without GUI and a Webbrowser. So I run the Canvas UI web page from my local Win 10. 
I would like to use a "cutom endpoint" to reach my VPS, but I think by default the Canvas node listents to 127.0.0.1:9944

How do you configure it to listen to an external IP?

**Comment by cmichi** [comment]
You can configure the Canvas UI to connect to a custom address here in the Settings:

![screenshot-paritytech github io-2021 08 30-06_26_29](https://user-images.githubusercontent.com/241530/131285206-823e5247-ee88-403a-82b0-caefd1e97bff.png)

You need to either ensure that your VPS is accessible via those ports or alternatively connect to your VPS via SSH whilst enabling port forwarding. This can be done via `ssh -L`, like described [in this](https://brson.github.io/2020/12/03/substrate-and-ink-part-2) blog post.

Do you get it to work this way?

**Comment by claudiociardelli** [comment]
Thank you for the advice. I struggled with SSH -L so at the end I setup a
remote desktop via X2GO and managed to make it work
