### ISSUE TITLE
in ink! workshop, Arch Linux and Mac installation instructions are provided, nothing for Debian

### ISSUE THREAD

**Issue by JonHill24** [substrate-developer-hub/substrate-contracts-workshop#28]
No installation help for wabt, pwasm or binaryen on Debian base linux distros 

![ink](https://user-images.githubusercontent.com/38847726/58647308-dcbfb000-82cc-11e9-8de9-fa2cce0585da.png)

**Comment by shawntabrizi** [comment]
Do you have a suggestion for content to add?

I don't have a debian system so idk.

Happy to merge a PR :)

**Comment by riusricardo** [comment]
@JonHill24 There is no standard way because the packages don't exist on Ubuntu/Debian.

You can run this script as a workaround:
``` bash
curl https://raw.githubusercontent.com/riusricardo/scripts/riusricardo-add-wasm-script/install-wasm-tools.sh -sSf |bash -s
```
@shawntabrizi Should I create a PR to merge this script?

**Comment by shawntabrizi** [comment]
Hmm, TBH I kind of hate scripts (and I kind of hate the ones used on Substrate).

Would rather have instructions which a user can follow, but if you think this is the right thing to do, open a PR, and I wouldn't be against merging it.

**Comment by shawntabrizi** [comment]
I merged @riusricardo's pr, so I will close this.
