### ISSUE TITLE
Substrate Contracts Workshop::Getting Started::Building Your Contract::./build.sh: *line 14: wasm-opt: command not found*

### ISSUE THREAD

**Issue by JonHill24** [substrate-developer-hub/substrate-contracts-workshop#32]
this is the build.sh command after the 'chmod +x build.sh' command. 

![error_ink](https://user-images.githubusercontent.com/38847726/59219504-44f17a00-8b88-11e9-9389-a33a14a619ae.png)

results in compilation with:
/build.sh: line 14: wasm-opt: command not found
-also my new directory in my flipper directory looks a little off
![error_ink1](https://user-images.githubusercontent.com/38847726/59219725-c47f4900-8b88-11e9-9aef-502107e6f307.png)
![error_ink2](https://user-images.githubusercontent.com/38847726/59219726-c47f4900-8b88-11e9-8b7f-cb974c430bce.png)

**Comment by JonHill24** [comment]
@riusricardo @shawntabrizi this came shortly after my other error

**Comment by riusricardo** [comment]
You need to update to the latest version of parity Ink contract. wasm-opt is no longer required.
Your build script should look like the one in the tutorial.

**Comment by riusricardo** [comment]
build.sh

```bash
#!/bin/bash
set -e

PROJNAME=flipper

# cargo clean
# rm Cargo.lock

CARGO_INCREMENTAL=0 &&
cargo build --release --features generate-api-description --target=wasm32-unknown-unknown --verbose
wasm2wat -o target/$PROJNAME.wat target/wasm32-unknown-unknown/release/$PROJNAME.wasm
cat target/$PROJNAME.wat | sed "s/(import \"env\" \"memory\" (memory (;0;) 2))/(import \"env\" \"memory\" (memory (;0;) 2 16))/" > target/$PROJNAME-fixed.wat
wat2wasm -o target/$PROJNAME.wasm target/$PROJNAME-fixed.wat
wasm-prune --exports call,deploy target/$PROJNAME.wasm target/$PROJNAME-pruned.wasm
```

**Comment by shawntabrizi** [comment]
Yup, this is the correct solution. Just update to the latest stuff of ink.
