### ISSUE TITLE
Outdated workshop docs?

### ISSUE THREAD

**Issue by alekspickle** [substrate-developer-hub/substrate-contracts-workshop#35]
I think this [workshop](https://substrate.dev/substrate-contracts-workshop/#/) needs some clarification in [this section](https://substrate.dev/substrate-contracts-workshop/#/1/incrementing-my-value).

I was able to understand some ink_core import logic through reading the source code, but completed this workshop only after completing [this one](https://substrate.dev/docs/en/contracts/env-types), where the old and new generic set_caller functions difference explained.

Maybe its intentional? I dont know.
Anyhow, its a matter of adding ```::<DefaultSrmlTypes>``` to the ```set_caller``` function, and if it is not intentional I can make PR.

**Comment by shawntabrizi** [comment]
@alekspickle indeed I think the workshop is out of date to the latest changes to `ink!`

If you want to make a PR that would be wonderful! Otherwise, I will have to take a look when I get time this week.

**Comment by alekspickle** [comment]
#36

**Comment by shawntabrizi** [comment]
Partially fixed, more in progress

**Comment by shawntabrizi** [comment]
https://github.com/substrate-developer-hub/substrate-contracts-workshop/pull/39
