### ISSUE TITLE
Link leads to 404 site

### ISSUE THREAD

**Issue by krichard410** [substrate-developer-hub/substrate-contracts-workshop#67]
If you click on 'installation instructions' in Substrate prerequisites section on this page: https://substrate.dev/substrate-contracts-workshop/#/0/setup 
it leads to a 404 page.

**Comment by danforbes** [comment]
@JoshOrndorff is it possible for us to address this along with https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/544? Not sure if the fact that they are in different repos complicates things too much.

**Comment by JoshOrndorff** [comment]
This broken link is fixed in #68.

@danforbes I don't think it makes sense / is practical to combine link checking here with the link checking in the main devhub repo. That being said, we could add link checking here as well.

**Comment by danforbes** [comment]
Yep, agree. Are there any other repos like this that we need to bring up to speed?
