### ISSUE TITLE
Compile of Node Template fails

### ISSUE THREAD

**Issue by Rexk99** [substrate-developer-hub/substrate-contracts-workshop#75]
Hi my compile is failing when I use: 
cd substrate-node-template/
cargo build --release

I am getting:
error[E0282]: type annotations needed
.
.
.
let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type

I have updated rust to nightly as suggested
I have followed the tutorial step-by-step:
https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup

Intel machine running debian buster

any help would be appreciated

**Comment by h4x3rotab** [comment]
Reproduce

```bash
git clone https://github.com/paritytech/substrate.git
cd substrate
cargo build --release
```

Failed with toolchains:
- stable-x86_64-unknown-linux-gnu (default)
- rustc 1.46.0 (04488afe3 2020-08-24)

The standalone packages can build:

```bash
cargo build --release -p sp-arithmetic
cargo build --release -p sp-utils
```

**Comment by shawntabrizi** [comment]
@Rexk99 it seems that the latest Rust Nightly version has broken Substrate compilation.

Try running:

```
rustup toolchain install nightly-2020-08-23
rustup default nightly-2020-08-23
```
