### ISSUE TITLE
flipper tutorial not working

### ISSUE THREAD

**Issue by zor98328** [substrate-developer-hub/substrate-contracts-workshop#76]
i ran flipper totorial, i can't upload wasm.

curl https://getsubstrate.io -sSf | bash -s -- --fast
rustup target add wasm32-unknown-unknown --toolchain stable
rustup component add rust-src --toolchain nightly
rustup toolchain install nightly-2020-08-24
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-24

cargo +nightly-2020-08-24 install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0 --force --locked
cargo install cargo-contract --vers 0.6.2 --force

cargo contract new flipper

cargo +nightly-2020-08-24 test
cargo +nightly-2020-08-24 contract build
cargo +nightly-2020-08-24 contract generate-metadata

substrate --dev
docker run --rm -it --name polkadot-ui -e WS_URL=ws://127.0.0.1:9944 -p 80:80 jacogr/polkadot-js-apps:0.60.1

but i can't upload wasm.
![image](https://user-images.githubusercontent.com/72492020/95819657-1b86c680-0d59-11eb-9a9a-d8244af7d313.png)
![image](https://user-images.githubusercontent.com/72492020/95819869-8506d500-0d59-11eb-9eaf-cd4cecfe49a4.png)
![image](https://user-images.githubusercontent.com/72492020/95819688-280b1f00-0d59-11eb-8c7b-1144ca13bb4b.png)
![image](https://user-images.githubusercontent.com/72492020/95819767-512baf80-0d59-11eb-9713-b8cc8c05a0d5.png)

**Comment by wheresaddie** [comment]
@jimmychu0807 @riusricardo

**Comment by riusricardo** [comment]
Unfortunately ink! 2.1 and Cargo contract 0.6.2 aren't compatible with Substrate v2.0.0

The tutorial is getting updates to match ink! 3.0 (releasing soon) and Substrate v2.0.0

**Comment by wheresaddie** [comment]
thanks @riusricardo .. @zor98328 going to close this issue for now, please standby for the tutorial updates and feel free to drop another issue if you have further problems or visit the riot forms for more 'real time' QA ( https://substrate.dev/en/community ) .. . thanks!
