### ISSUE TITLE
Definition of Array , Structure and String

### ISSUE THREAD

**Issue by svrapidinnovation** [substrate-developer-hub/substrate-contracts-workshop#77]
When I am defining String , It's gives an error " not found in scope".I also want to know how can we define dynamic array and structure in ink.

**Comment by shirshak55** [comment]
did you use https://paritytech.github.io/ink/ink_prelude/string/struct.String.html for String? Its on prelude. 

By Dynamic Array you probably mean Vec which is allowed.

**Comment by shirshak55** [comment]
@wheresaddie  Close the issue?
