### ISSUE TITLE
ink! setup compile problem: dispatcher.rs:186:30

### ISSUE THREAD

**Issue by Maar-io** [substrate-developer-hub/substrate-contracts-workshop#78]
Following steps in [ink! tutorial](https://substrate.dev/substrate-contracts-workshop/#/) I get following compile problem.
To be sure that it is not due to my macOs setup, I repeated all steps as [github-workflow](https://github.com/Maar-io/test-contract-env/runs/1247871503?check_suite_focus=true) by running ubuntu and got the same compile problem.

-----------------------
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-06-01-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

--------------------------------------
Compiling ink_core v2.1.0 (https://github.com/paritytech/ink?tag=latest-v2#cca31543)
   Compiling ink_lang v2.1.0 (https://github.com/paritytech/ink?tag=latest-v2#cca31543)
error[E0658]: function pointers cannot appear in constant functions
   --> /home/runner/.cargo/git/checkouts/ink-1add513eda8f5a89/cca3154/lang/src/dispatcher.rs:186:30
    |
186 |               pub const fn new(dispatchable: $dispatchable_fn<Msg, S>) -> Self {
    |                                ^^^^^^^^^^^^
...
237 | / impl_dispatcher_for! {
238 | |     /// Dispatcher for storage preserving messages.
239 | |     struct Dispatcher(DispatchableFn);
240 | | }
    | |_- in this macro invocation
    |
    = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
    = help: add `#![feature(const_fn_fn_ptr_basics)]` to the crate attributes to enable
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by wheresaddie** [comment]
hi @Maar-io -- 

afaik ink! 2.1 and Cargo contract 0.6.2 aren't compatible with Substrate v2.0.0 

The tutorial is getting updates to match ink! 3.0 (releasing soon) and Substrate v2.0.0

In the meantime, if you're not already I encourage you to ping the Riot channels for more real time QA/updates if you're not already around ( https://substrate.dev/community ) 

I am closing this issue but feel free to open it up or start another if you have additional issues. thanks!

cc @danforbes

**Comment by danforbes** [comment]
@Maar-io what command are you running when you encounter this error? As Addie mentioned, ink! 3.0 is imminent and will be debuted at [Sub0](https://sub0.parity.io/). This tutorial should be updated around that time. Ref https://github.com/substrate-developer-hub/substrate-contracts-workshop/pull/73

cc @Robbepop

**Comment by Maar-io** [comment]
Hi Dan,

last command that fails is:
cargo +nightly test

**Comment by danforbes** [comment]
Can you try this? `cargo +nightly-2020-06-01 test`

**Comment by Maar-io** [comment]
@danforbes, you make me happy :) THANKS!!!
I can finally start playing with ink!

@wheresaddie, thanks for help, I will join the Riot
