### ISSUE TITLE
Section 1 - Use solely i32 throughout codebase

### ISSUE THREAD

**Issue by pmuens** [substrate-developer-hub/substrate-contracts-workshop#83]
In [section 1](https://github.com/substrate-developer-hub/substrate-contracts-workshop/tree/master/1) we use the `i32` data the throughout the first half of the tutorials.

However when starting to work on the `HashMap` implementation there's a switch to use `u64` for functions which involve manipulations of such `HashMap`.

Is there a reason for doing this? Or is it maybe an artifact from older tutorial revisions?

I'd propose to keep it consistent and switch the HashMap from `my_value: ink_storage::collections::HashMap<AccountId, u64>` to `my_value: ink_storage::collections::HashMap<AccountId, i32>`.

Just let me know if that's reasonable and I can PR the necessary changes.

**Comment by wheresaddie** [comment]
going to defer to @riusricardo on naming conventions

**Comment by pmuens** [comment]
Thanks @wheresaddie 👍 

For reference here's the [full implementation](https://github.com/pmuens/inking/blob/master/incrementer/lib.rs) of the `incrementer` project I'm referring to.

**Comment by riusricardo** [comment]
Thanks for the heads-up. Sometimes we try to use one type in the explanation and change it in the implementation. The main idea is to demonstrate ink!'s capabilities on handling signed and unsigned integers. It is up to the reader to understand the explanation and then see that it can be used in a broader way.

**Comment by Robbepop** [comment]
> Thanks for the heads-up. Sometimes we try to use one type in the explanation and change it in the implementation. The main idea is to demonstrate ink!'s capabilities on handling signed and unsigned integers. It is up to the reader to understand the explanation and then see that it can be used in a broader way.

I think @pmuens got a good point here. A workshop also targets people that might need guidance. Think about people that are not fluent in Rust already. Therefore our workshop should take those people by hands and explain things to them in great detail. For every other audience just reads the more technical documentation of ink!.

**Comment by riusricardo** [comment]
Fair point @Robbepop I was quite neutral to this. I do agree that can be a little bit confusing for the first time, also don't see it as a stopper. @pmuens please feel free to open a PR to address it as it best makes sense for you. Your feedback is much appreciated.

**Comment by pmuens** [comment]
Hey @wheresaddie @riusricardo and @Robbepop thanks for chiming in!

> Sometimes we try to use one type in the explanation and change it in the implementation. The main idea is to demonstrate ink!'s capabilities on handling signed and unsigned integers. It is up to the reader to understand the explanation and then see that it can be used in a broader way.

Yes, I can totally see that. Having maximum exposure to `ink!`'s capabilities is a really good idea. I guess my main confusion rooted in the fact that introducing another numerical data type didn't provide any additional value. Maybe the section can be further enhanced where one starts with `i32`, runs into a roadblock which is then solved by introducing a `u64` (or the other way around).

I just PRed #84 which updates the code. Let me know if there's anything else I can help you with...

**Comment by wheresaddie** [comment]
just pushed the PR #84 thanks @pmuens
