### ISSUE TITLE
failed to run custom build command for `binaryen-sys v0.12.0`

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/substrate-contracts-workshop#98]
So I've worked through these tutorials:

* https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/
* https://substrate.dev/docs/en/tutorials/add-a-pallet/
* https://substrate.dev/docs/en/tutorials/add-contracts-pallet

and so now I'm trying to learn about ink and contracts to actually play with contracts on the system I've setup and modified via these three tutorials, so following the link in the last one I am now on this tutorial

https://substrate.dev/substrate-contracts-workshop/#/0/setup

where I'm a little confused about which of the setup pre-requisites are needed given that I set a load of things up in the tutorials.  I thought maybe I could just get away with adding the "Ink! CLI", and I had a little trouble installing that, specifically:

```
error: failed to run custom build command for `binaryen-sys v0.12.0`

Caused by:
  process didn't exit successfully: `/var/folders/37/4_sjt6h17yqgvnpy12wzpk4c0000gn/T/cargo-installFV5x9c/release/build/binaryen-sys-5af70631e678c29a/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/binaryen-sys-0.12.0/binaryen" "-DBUILD_STATIC_LIB=ON" "-DENABLE_WERROR=OFF" "-DCMAKE_INSTALL_PREFIX=/var/folders/37/4_sjt6h17yqgvnpy12wzpk4c0000gn/T/cargo-installFV5x9c/release/build/binaryen-sys-5552a857dd5f43cb/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-contract v0.8.0`, intermediate artifacts can be found at `/var/folders/37/4_sjt6h17yqgvnpy12wzpk4c0000gn/T/cargo-installFV5x9c`

Caused by:
  build failed
```

I managed to fix this on OSX 11.1 by doing the following:

```
brew install cmake
```

but I'm still not sure if wanted to be installing this.  I ran it in the `substrate-developer-hub/substrate-node-template` folder and I'm not entirely clear if this is installing something on my system globally or if it's adding something to the node template?

Any which way, might it make sense to have a section in https://substrate.dev/substrate-contracts-workshop/#/0/setup for those coming from the tutorials?

**Comment by cmichi** [comment]
@tansaku Thanks for the pointer, I've just created a PR to update the workshop!

Have you gotten it running in the meantime? If not: The issue is that `cargo-contract` requires the `binaryen` package. Many package managers have it available nowadays ‒ e.g. it's a package for [Debian/Ubuntu](https://tracker.debian.org/pkg/binaryen), [Homebrew](https://formulae.brew.sh/formula/binaryen) and [Arch Linux](https://archlinux.org/packages/community/x86_64/binaryen/).

**Comment by nuke-web3** [comment]
Looks like we are set here? If not, please let's open a new issue and reference this in:
https://github.com/substrate-developer-hub/substrate-docs/issues/
